version: '3.7'

services:
  db:
    image: postgres

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - minio-data:/export
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server start object storage server
    
  server:
    build: ./backend
    image: qoutland/django-react_backend
    command: sh -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    links:
      - db
      - minio
    depends_on:
      - db
      - minio

  frontend:
    build: ./frontend
    image: qoutland/django-react_frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend/src:/var/node/src
      - ./frontend/public:/var/node/public
    links: 
      - server
    command: npm start
    depends_on:
      - server

volumes:
  minio-data: