version: '3'

services:
  db:
    image: postgres

  server:
    build: ./backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend/src:/var/node/src
      - ./frontend/public:/var/node/public
    links: 
      - server
    command: npm start
    depends_on:
      - server
